version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopper-database
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
